name: Heroku Deploy

on:
  push:
    branch:
      - main

jobs:
  heroku-dev:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2

      - name: Render env file
        uses: nowactions/envsubst@v1
        with:
          input: ./.env.tpl
          output: ./.env
        env:
          FOO: fool

      - name: Check env
        run: |
          cat ./.env
          echo "\nFOO is ${FOO}"
          echo "\nBAR is ${secrets.BAR}"
